data_preprocessing:
  path: data/test_generated_data.csv
  test_size: 0.3
  shuffle: True
  random_state: 888
  skiped_columns: []

  train_data_path: tests/test_data/X_train.npy
  train_targer_path: tests/test_data/Y_train.npy
  test_data_path: tests/test_data/X_test.npy
  test_targer_path: tests/test_data/Y_test.npy

train:
  train_data_path: tests/test_data/X_train.npy
  train_targer_path: tests/test_data/Y_train.npy
  
  algorithm: "logigstic_regression" # logigstic_regression, decision_tree, random_forest
  logigstic_regression: 
    penalty: 'l2'
    C: 1.0
    solver: 'lbfgs' 
    max_iter: 100

  decision_tree:
    criterion: 'gini'
    splitter: 'best'
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1

  random_forest:
    n_estimators: 100
    criterion: 'gini'
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1

  model_save_path: tests/test_data/model.pickle

eval:
  model_path: tests/test_data/model.pickle
  test_data_path: tests/test_data/X_test.npy
  test_targer_path: tests/test_data/Y_test.npy