apiVersion: v1
kind: Service
metadata:
  name: online-inference-service
spec:
  selector:
    app: online-inference
  ports:
    # - protocol: TCP
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-rs
  labels:
    app: online-inference-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
      - name: online-inference
        image: nekronix588/made-inference-mlops:latest
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
        ports:
        - containerPort: 8000